django/web/chart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chart_view, name='chart_view'),  # /chart/ 경로에 대응하는 뷰 설정
]

django/web/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # home 앱의 URL 설정 포함
    path('chart/', include('chart.urls')),  # chart 앱의 URL 설정 포함
]

django/web/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
  
]

django/web/chart/models.py
from django.db import models

# Create your models here.

django/web/home/models.py
from django.db import models

# Create your models here.

django/web/chart/views.py
from django.shortcuts import render
import MySQLdb
from django.http import JsonResponse
import json


def chart_view(request):
    '''
    db_config = {
        "host" : "43.202.5.70", 
        "user" : "class5",
        "password" : "EnCoRo!23",
        "database" : "encore_web" 
    }
    con = MySQLdb.connect(**db_config)
    cur = con.cursor()

    cur.execute("select * from result")
    data = cur.fetchall()
    cur.close()
    con.close()

    labels    = [x[0] for x in data]
    Cancelled = [x[1] for x in data]
    Divered   = [x[2] for x in data]
    Air       = [x[3] for x in data]

    datasets = [
        {'label' : 'Cancelled', 'data' : Cancelled, 'backgroundColor': 'rgba(255, 99, 132, 0.5)' },
        {'label' : 'Divered',   'data' : Divered,   'backgroundColor': 'rgba(54, 160, 235, 0.5)' },
        {'label' : 'Air',       'data' : Air,       'backgroundColor': 'rgba(75, 199, 192, 0.5)' },
    ]

    chart_data = {
        'labels' : labels,
        'datasets' : datasets
    }
    '''
    return render(request, 'chart/chart.html')

django/web/home/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    #return HttpResponse("첫 화면이 될 페이지")
    return render(request, 'home/index.html')

django/web/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
    <title>title</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
 <!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.css' %}"></script>
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

django/web/templates/chart/chart.html
<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <title>chart.js</title>
    
    <body>
        <h1>차트부분</h1>
    </body>
</html>

django/web/templates/home/index.html
{% extends 'base.html' %}

{% block content %}    
    <form method="GET">
        <div class="searchForm">
            <input type="date" name="input-date" id="date">
            <input type="submit" id="btnSearch" value="워드클라우드보기">
            <input type="submit" id="btnSearch" value="차트보기">
            
        </div>
    </form>
    
{% endblock %}        

django/web/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar">

    <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
    </button>
        
    
</nav>